### PR TITLE
Ch13 translation

### PR DESCRIPTION
**Pull request by asettouf**
Hello,

not sure exactly where to put it, and here seems the most convenient place. I finished translating the chapter 13, so if anyone wants to give it a good review, that would be nothing less than awesome.

Cheers,

Adonis

### CODE REVIEW

**Comment by quadrifoglio** [comment]
Merged. Thanks :D

**Comment by Jimskapt** [comment]
Hi, team !

@quadrifoglio I think it would be better to wait that another people than translator proofreading the chapter before merging it to master, no ?

@asettouf I think I will take time this week-end to proofreading the chapter 13 ;-)

By the way, the chapter 04 and 09 are also ready to proofreading.

Do we keep this PR system, or we create tickets like "proofreading chapter 13" in our [project ticket panel](https://github.com/quadrifoglio/rust-book-fr/projects/1) in order to book it ?

**Comment by asettouf** [comment]
@Jimskapt Completely agree on the proofreading. I think PRs are fine given that we commit to a branch. What would tickets add to the process?

I'll give you're a reading then

**Comment by Jimskapt** [comment]
> What would tickets add to the process?

@asettouf  In fact, nothing very useful, just that you know that someone proofreading it ! Also, it will block proofreading to one people. I think we can do without it.

If we are working with tickets instead of PRs, that means that we have to regulary take look at the panel to see progresses. Or maybe the thing is hackable to send notifications when a ticket fall in a column (like the last) ?

**Comment by asettouf** [comment]
@Jimskapt Actually that has some advantages over a PR.

I believe we could as well set the repository to accept merging only after a review has validated the PR, as someone could signal directly on the PR that he/she takes the review and then validate (or not) and comment on the modifications directly.

One of the thing that might be annoying is that PRs and the frozen panel does not seem to be well integrated as opposed to PRs and Issues...

**Comment by quadrifoglio** [comment]
So, if I understand you correctly, we could setup the following process:

Once a chapter is fully translated by one (or more) person, he/she opens a PR, that serves as a place for tracking the validation process. Anyone wishing to proofread, comment and provide corrections can do so in the PR. When they are satisfied with the current state of the chapter, they indicate so by giving a thumbs up. It is then collectively decided when to merge in master.

I do think that PRs are preferable to issues, even without the board integration, as updating the project board is something that can easily and quickly be done, but I might be wrong on that.

Does that seem acceptable ?

**Comment by asettouf** [comment]
@quadrifoglio 

For sure, this process looks fine to me. Actually on the PR you can even ask for review (top right)

**Comment by Jimskapt** [comment]
Yep, the thumbs up is a nice idea !
This process is OK for me too, if we have the hability to edit the text in the PR's branch (before merge) ?
Sorry for this point, I've never worked with PRs ;-)

**Pull request merged**
